### ISSUE TITLE
Volunteering with Codedocs

### ISSUE THREAD

**Issue by accakks** [CodeDocsJECRC/society#67]
Hi, I would like to volunteer in:

Presently

1) Maintaining github.org
2) Members relationship manager
3) Events Organisation

Upcoming:
4) Later/Eventually, maintenance of the website and checking assignments. Also, From July onwards, I'd like to conduct sessions for girls with Codedocs and Lean In, but I'll propose about those later.

Apart from that, I can maintain a blog for Codedocs & its events if needed.

**Comment by accakks** [comment]
Also, I have admin access to hackerearth  test and hackathons conduction for Jecrc. So I can help in setting up tests if we wish to use hackerearth as platform.

**Comment by maddhruv** [comment]
Hey @accakks we are expecting-
1. Maintainance of Github org -> adding users to the organisation (inviting them to join) and adding to members team by default. The members lately added in society are to be added. Assigning them teams, repos etc
2. Members relationship manager - listening to help, creating repo for new projects, tracking or summarising activities of members
3. Events - volunteering in events

**Comment by maddhruv** [comment]
> So I can help in setting up tests if we wish to use hackerearth as platform.

We have planned some tests for **CD101** and will sure contact you regarding this
/cc @CodeDocsJECRC/community-committee

**Comment by accakks** [comment]
@maddhruv _I think I do not have rights to invite members._ **Rest noted.**

**Comment by maddhruv** [comment]
Promoted
