### ISSUE TITLE
Seeking Github ORG Maintainer

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/society#76]
The job will be to manage all the current repositories, add new.
You would have to invite new members to the Org, stay in relation with all the members and manage them.

### Skills Required
- Throughout knowledge of **GIT** and **Github**

**Comment by accakks** [comment]
Working on it!

**Comment by AmanBansal1998** [comment]
I am willing to work on it. 💯💯

**Comment by maddhruv** [comment]
@accakks is working over it
closing
