### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by Abhimanyu121** [CodeDocsJECRC/society#77]
I would like to make and maintain android app of code docs

**Comment by maddhruv** [comment]
Thanks for this idea, wonderful seeing you volunteering.
We will create a repository for the same.

With meeting first we should decide the wireframes, content structures, and UI for the app. And as we collect all the necessary stuffs, would start the Development Process

**Comment by maddhruv** [comment]
@Abhimanyu121 
we have created a separate repository for the *app*
please check out https://github.com/CodeDocsJECRC/CodeDocs-App

**Comment by shiv-k-sharma** [comment]
I would love to contribute to the same

**Comment by maddhruv** [comment]
Check the above mentioned repository and attend today's meeting

**Comment by maddhruv** [comment]
closing in reference to https://github.com/CodeDocsJECRC/CodeDocs-App
