### ISSUE TITLE
New leaders/core team members addition from 3rd year 2018-19

### ISSUE THREAD

**Issue by accakks** [CodeDocsJECRC/society#90]
As we're heading towards end of this session, I (and I believe many others) would like to take CodeDocs forward to next session. For this we need new team formation from 3rd year. 
I'd be interested to lead too, speaking for myself. 

@maddhruv

**Comment by dhruvshridhar** [comment]
I wish to contribute whatever I can for CodeDocs.

**Comment by amritsrivastava** [comment]
Would love to join the team.

**Comment by tarangrai08** [comment]
I would like to join the team . In 2year codedocs held an event and i am volunteer of this event.

**Comment by soumilk** [comment]
It's a great initiative, and I would love to be a part of it.

**Comment by nd-singh** [comment]
It will be an honour to contribute to CodedocsJecrc.
Regards
Namandeep Singh
2 nd yr CS

**Comment by himanshudamani** [comment]
I wish to contribute whatever I can for CodeDocs.

**Comment by samyak360** [comment]
I would love to join the team.

**Comment by AmanBansal1998** [comment]
Yes! , definitely I would like to be the part of CodeDocs in future . 😊
Great team , great initiative.

**Comment by maddhruv** [comment]
Awesome seeing many of you heading volunteerely and ready to lead CodeDocs ahead towards the Vision of teaching students in the college and creating an environment of programming and P2P learning.

Thanks, @accakks for raising this issue.

The **lead** / **chair persons** would be responsible for:
- Teaching/Teaching assistant for Web and Android
- Maintain the website
- Lead initiatives
- Organize and Conduct events
- Grow Relations with outer world and partners

@aditya81070 @dhruvshridhar @amritsrivastava @tarangrai08 @soumilk @nd-singh @himanshudamani @samyak360 @AmanBansal1998 thanks for showing interest but we are not yet decided with some reliable and honest procedure to choose heirs.

After helding a meeting with the @CodeDocsJECRC/community-committee we shal revert you the follow up for the same.

Stay tuned
:+1:

**Comment by luck-u** [comment]
I would also love to join the team

**Comment by accakks** [comment]
@maddhruv Exams for 2nd year got over today.

**Comment by maddhruv** [comment]
:tada: :tada: :tada: 
There's a green flag :green_heart: from the current @CodeDocsJECRC/community-committee 

Also, fill this doodle and lets find out a common day we can talk - https://doodle.com/poll/d2arv74fvcd5maf3

May be on Phone call or conference call, which suits us best.

**Comment by accakks** [comment]
Is it possible to do the call today? or next wednesday has most upvotes! @maddhruv

**Comment by Hitesh98765** [comment]
Sir/ma'am
You can call me today regarding codedocs recruitment. If possible than
please inform me the time interval in which you will call so that if I get
any work in that period, i can skip that work.

Thank you

**Comment by aditya98ak** [comment]
Would love to have an opportunity to work w/ y'all. 
Cheers!
Aditya Kaushik, CSE 3rd Year

**Comment by aditya98ak** [comment]
Email: adityakaushik.cse20@jecrc.ac.in

**Comment by maddhruv** [comment]
Check that up!

**Comment by dgupta777** [comment]
I would also like to join the team

**Comment by maddhruv** [comment]
Whosoever wants to be a part/member please share your email so that I can forward you the next instructions to follow up

**Comment by dgupta777** [comment]
darshitgupta777@gmail.com

**Comment by dhruvshridhar** [comment]
dhruvshridhar@gmail.com

**Comment by luck-u** [comment]
lakshaywadhwa001@gmail.com



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/06/18,
13:20:28

**Comment by abhilashk433** [comment]
Would love to be a part of Code docs team.
Abhilash, 3rd year, CSE
abhilashkumartiwari.cse20@jecrc.ac.in

**Comment by Hitesh98765** [comment]
Email:- hwasdani@gmail.com

**Comment by nd-singh** [comment]
It would be an honour to be a part of codedocs.
Email-ndsingh208@gmail.com
Namandeep Singh,CSE,3 rd yr.

**Comment by amritsrivastava** [comment]
Email - srivastava.amrit1999@gmail.com

**Comment by maddhruv** [comment]
Not accepting more Applications

Also, I have sent the email to everyone of you above.

Please respond to the email as early as possible

**Comment by maddhruv** [comment]
closing in favour of https://github.com/CodeDocsJECRC/community-committee/issues/12
